name: Tests-extended

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run test runner (story store v7)
        run: |
          yarn build
          STORY_STORE_V7=true yarn test-storybook:ci

      - name: Run test runner (stories json mode)
        run: |
          yarn build
          yarn test-storybook:ci-json
