name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run jest tests
        run: |
          yarn test --coverage

      - name: Run test runner
        run: |
          yarn build
          yarn test-storybook:ci-coverage

      - name: Generate code coverage
        uses: codecov/codecov-action@v2
        with:
          verbose: true
